tuya/tuya-panel-sdk

packages/tuya-panel-lock-sdk/src/defend-time/i18n/index.ts
packages/tuya-panel-lock-sdk/src/defend-time/i18n/string.ts
packages/tuya-panel-lock-sdk/src/defend-time/index.tsx
packages/tuya-panel-lock-sdk/src/get-password/index.tsx

:bug: fix/defend-time:解决多语言问题

---

packages/tuya-panel-api/README-zh_CN.md
packages/tuya-panel-api/README.md
packages/tuya-panel-api/src/common/alarm.ts
packages/tuya-panel-api/src/common/currency.ts
packages/tuya-panel-api/src/common/device.ts
packages/tuya-panel-api/src/common/interface.ts
packages/tuya-panel-api/src/common/linkage.ts
packages/tuya-panel-api/src/common/scene.ts
packages/tuya-panel-api/src/common/statistic.ts
packages/tuya-panel-api/src/common/timer.ts
packages/tuya-panel-api/src/robot/gyroDataApi.ts
packages/tuya-panel-api/src/robot/laserDataApi.ts
packages/tuya-panel-api/src/robot/laserUiApi.ts
packages/tuya-panel-api/src/robot/ossDataApi.ts

feat(interface): 补充commonApi类型提示
feat(laserbitmaptoimagebase64): 补充返回值类型
docs(readme): 修订文档地址

feat(interface): 添加返回值类型

---

.github/workflows/auto-add-reviewer.yml

chore: fix ci typo

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-native/playManager.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/interface.ts

feat: add initStatus, isMuting, isRecording, isTalkBacking, isHDOn methods

---

.eslintrc.js
README-zh_CN.md
README.md
packages/tuya-panel-api/README-zh_CN.md
packages/tuya-panel-api/README.md
packages/tuya-panel-api/src/gateway/index.ts
packages/tuya-panel-api/src/gateway/interface.ts
packages/tuya-panel-api/src/gateway/relation.ts
packages/tuya-panel-api/src/index.ts

Add two gateway relation update api, this is the list of these api urls: 
'tuya.m.device.relation.update.for.ble',
'tuya.m.device.relation.update'

feat: add gateway relation api

---

packages/tuya-panel-api/src/common/interface.ts

Adaptation of cloud interface changes

feat: adaptation of cloud interface changes

---

packages/tuya-panel-api/src/common/device.ts
packages/tuya-panel-api/src/common/interface.ts

feat: add IGetWeatherQuality_1

---

example/src/scenes/Gateway/index.js
packages/tuya-panel-gateway-sdk/@types/index.d.ts
packages/tuya-panel-gateway-sdk/src/config/index.ts
packages/tuya-panel-gateway-sdk/src/index.js
packages/tuya-panel-gateway-sdk/src/utils/index.ts

feat: add gateway util library

---

example/src/scenes/Ipc/IpcPlayer/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/cameraData.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/playManager.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/i18n/string.ts
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

Add iosSnapShootToPhoneAlbums, pausePlay method.
Don't edit this section

add iosSnapShootToPhoneAlbums, pausePlay method

---

example/src/scenes/Gateway/TopBarWithArc/i18n/index.ts
example/src/scenes/Gateway/TopBarWithArc/i18n/strings.ts
example/src/scenes/Gateway/TopBarWithArc/index.tsx
example/src/scenes/Lock/index.js
example/src/scenes/Lock/weekSelection/index.js
packages/tuya-panel-lock-sdk/package.json
packages/tuya-panel-lock-sdk/src/index.js
packages/tuya-panel-lock-sdk/src/week-selection/__tests__/__snapshots__/weekSelection.test.js.snap
packages/tuya-panel-lock-sdk/src/week-selection/__tests__/weekSelection.test.js
packages/tuya-panel-lock-sdk/src/week-selection/i18n/index.ts
packages/tuya-panel-lock-sdk/src/week-selection/i18n/strings.ts
packages/tuya-panel-lock-sdk/src/week-selection/index.tsx
packages/tuya-panel-lock-sdk/src/week-selection/interface.ts
packages/tuya-panel-lock-sdk/src/week-selection/utils/index.ts

Feature/tuya panel lock sdk/week selection

---

example/src/config/routers.js
packages/tuya-panel-ipc-sdk/src/ty-ipc-message-player/tyIpcMessagePlayer.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-message-player/utils/index.tsx

fix the bug of ipc message player
Don't edit this section.

fix the bug of ipc message player

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx

Talkback method export error message.
Don't edit this section.

fix: Talkback method export error message.

---

example/src/config/routers.js
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

Fix: native module can not found.

fix: native module can not found

---

example/src/scenes/Lamp/ConicalGradient/index.tsx
example/src/scenes/Lamp/index.js
packages/tuya-panel-lamp-sdk/package.json
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/Android.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/Ios.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/Normal.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/__tests__/__snapshots__/index.test.js.snap
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/index.android.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/index.ios.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/index.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/index.web.tsx
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/interface.ts
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/utils.ts
packages/tuya-panel-lamp-sdk/src/components/index.ts
packages/tuya-panel-lamp-sdk/src/components/picker/circle-picker/index.tsx
packages/tuya-panel-lamp-sdk/src/components/slider/bright-rect-slider/index.tsx
packages/tuya-panel-lamp-sdk/src/components/slider/number-slider/index.tsx
yarn.lock

Add new component: ConicalGradient. fix bug of NumberSlider, CirclePicker and BrightRectSlider

feat: add ConicalGradient and fix slider

---

example/src/scenes/Gateway/AddProgress/i18n/strings.ts
example/src/scenes/Gateway/AddProgress/index.tsx
example/src/scenes/Gateway/DeviceListPanel/index.tsx
packages/tuya-panel-gateway-sdk/@types/index.d.ts
packages/tuya-panel-gateway-sdk/src/components/addDeviceTip/index.tsx
packages/tuya-panel-gateway-sdk/src/components/addProgress/i18n/strings.ts
packages/tuya-panel-gateway-sdk/src/components/addProgress/index.tsx
packages/tuya-panel-gateway-sdk/src/components/addProgress/interface.ts
packages/tuya-panel-gateway-sdk/src/components/addProgress/style.ts
packages/tuya-panel-gateway-sdk/src/components/deviceListPanel/index.tsx
packages/tuya-panel-gateway-sdk/src/components/deviceListPanel/interface.ts
packages/tuya-panel-gateway-sdk/src/components/deviceListPanel/style.ts
packages/tuya-panel-gateway-sdk/src/components/selectDevice/index.tsx
packages/tuya-panel-gateway-sdk/src/components/selectDevice/interface.ts

Add some props in gateway components named "AddProgress" and "DeviceListPanel"

feat: add some props in gateway components named "AddProgress" and "DeviceListPanel"

---

example/src/main.js
example/src/scenes/Outdoor/index.js
example/src/scenes/Outdoor/swipe-pop/index.js
packages/tuya-panel-outdoor-sdk/src/components/swipe-pop/__tests__/__snapshots__/index.test.tsx.snap
packages/tuya-panel-outdoor-sdk/src/components/swipe-pop/__tests__/index.test.tsx
packages/tuya-panel-outdoor-sdk/src/components/swipe-pop/arrow.tsx
packages/tuya-panel-outdoor-sdk/src/components/swipe-pop/index.tsx
packages/tuya-panel-outdoor-sdk/src/components/swipe-pop/swipe.tsx
packages/tuya-panel-outdoor-sdk/src/index.js

add outdoor component swipe-pop

feat: add outdoor component swiper-pop

---

packages/tuya-panel-ipc-sdk/src/index.js
packages/tuya-panel-ipc-sdk/src/ty-ipc-message-player/tyIpcMessagePlayer.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native-module/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

1. add sessionDisconnect stream status
2. export all native modules

fix: 1. add sessionDisconnect stream status 2. export all native modules

---

packages/tuya-panel-lamp-sdk/src/components/music/music-drawer/__tests__/__snapshots__/music-drawer.test.js.snap
packages/tuya-panel-lamp-sdk/src/components/music/music-drawer/__tests__/music-drawer.test.js

fix: update musicDrawer test file

---

packages/tuya-panel-lamp-sdk/@types/index.d.ts
packages/tuya-panel-lamp-sdk/src/components/gradient/conical-gradient/Ios.tsx
packages/tuya-panel-lamp-sdk/src/formatter/cycleTiming/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/cycleTiming/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/powerMemory/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/powerMemory/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/randomTiming/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/randomTiming/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/sceneData/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/sceneData/index.ts
packages/tuya-panel-lamp-sdk/src/utils/dpCodes.ts

Add new dp formatter: CycleTimerFormatter, PowerMemoryFormatter, RandomTimerFormatter, SceneFormatter.

feat(lamp): add new dp formatter

---

packages/tuya-panel-api/src/lamp/general.ts
packages/tuya-panel-api/src/lamp/index.ts
packages/tuya-panel-api/src/lamp/storage.ts
packages/tuya-panel-api/src/lamp/timing.ts
packages/tuya-panel-api/src/lamp/utils.ts

Add new general api for lamp sdk

feat: add lamp general api

---

example/src/scenes/Ipc/IpcPlayer/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/nativeManager.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/interface.ts

Custom connection and pull flow

chore: del other jest file

---

example/src/scenes/Ipc/IpcPlayer/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/playManager.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx

feat: float window

---

.eslintrc.js
packages/tuya-panel-api/src/gateway/interface.ts
packages/tuya-panel-api/src/gateway/relation.ts
packages/tuya-panel-gateway-sdk/@types/index.d.ts
packages/tuya-panel-gateway-sdk/src/components/deviceListPanel/index.tsx
packages/tuya-panel-gateway-sdk/src/utils/index.ts

Fix the problem that the component deviceListPanel may be slow sometimes.

feat(gateway): Add a new open API of gateway.

---

example/babel.config.js
example/src/i18n/strings.js
example/src/scenes/Lamp/TimeFormatComponent/index.tsx
example/src/scenes/Lamp/TimingRepeatList/index.tsx
example/src/scenes/Lamp/index.js
packages/tuya-panel-lamp-sdk/@types/index.d.ts
packages/tuya-panel-lamp-sdk/src/components/index.ts
packages/tuya-panel-lamp-sdk/src/components/list/color-selector-animation/Btn.tsx
packages/tuya-panel-lamp-sdk/src/components/list/color-selector-animation/Circle.tsx
packages/tuya-panel-lamp-sdk/src/components/list/color-selector-animation/index.tsx
packages/tuya-panel-lamp-sdk/src/components/list/color-selector-animation/interface.ts
packages/tuya-panel-lamp-sdk/src/components/time-format-component/__tests__/__snapshots__/index.test.js.snap
packages/tuya-panel-lamp-sdk/src/components/time-format-component/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/components/time-format-component/index.ts
packages/tuya-panel-lamp-sdk/src/components/time-format-component/rangeTime.tsx
packages/tuya-panel-lamp-sdk/src/components/time-format-component/singleTime.tsx
packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/__tests__/__snapshots__/index.test.js.snap
packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/i18n/index.ts
packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/i18n/string.ts
packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/index.tsx
packages/tuya-panel-lamp-sdk/src/formatter/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/rtcTimer/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/rtcTimer/default.ts
packages/tuya-panel-lamp-sdk/src/formatter/rtcTimer/index.ts
packages/tuya-panel-lamp-sdk/src/formatter/switchGradient/__tests__/index.test.js
packages/tuya-panel-lamp-sdk/src/formatter/switchGradient/index.ts

feat(lamp): add component formatter

---

packages/tuya-panel-gateway-sdk/package.json
packages/tuya-panel-ipc-sdk/package.json
packages/tuya-panel-lamp-sdk/package.json
packages/tuya-panel-lock-sdk/package.json
packages/tuya-panel-outdoor-sdk/package.json
packages/tuya-panel-remote-sdk/package.json
packages/tuya-panel-robot-sdk/package.json
packages/tuya-panel-szos-sdk/package.json

Remove the single quotes surrounding the paths

fix(windows): Remove the single quotes surrounding the paths

---

packages/tuya-panel-lamp-sdk/src/formatter/rtcTimer/index.ts

fix(lamp): fix rtcTimer

---

packages/tuya-panel-lamp-sdk/src/components/timing-repeat-list/index.tsx

fix component TimingRepeatList

fix(lamp): fix component TimingRepeatList

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-native/nativeManager.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/i18n/string.ts

Correct intercom status and i118n

fix: Correct intercom status

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

feat: Network change.

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-grid-list/__tests__/__snapshots__/tyIpcGridList.test.js.snap
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/utils/index.tsx

fix: 修改容器品类

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-grid-list/__tests__/__snapshots__/tyIpcGridList.test.js.snap
packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx

fix: 修复ios旋转问题

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/interface.ts

feat: add cancelSessionEmit param

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/interface.ts

Add attribute displayInPortrait

feat: add attribute displayInPortrait

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

1. Component object merge repair

fix: Component object merge repair

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx

fix: ios orientationManager fix

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx

fix: Adaptation by Width for ios

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-native/player-manager-func.tsx

add useIpccontainer属性

---

packages/tuya-panel-ipc-sdk/src/ty-ipc-player/components/audioOnlyMode.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/components/playerLoad.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/index.tsx
packages/tuya-panel-ipc-sdk/src/ty-ipc-player/interface.ts

1. add useCustomContainer props

fix: add useCustomContainer
